name: sample-workflow

on:
  pull_request:

permissions:
  contents: read

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      # Need to checkout for testing the Action in this repo
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3.0.2
        with:
          fetch-depth: 0 # needed to checkout all branches

      # Start check the PR diff
      - uses: ./
        id: git-diff-action

      # Print the diff in JSON format
      - name: echo json diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff }}
        run: |
          echo $DIFF
          echo $DIFF > ~/diff.json

      # Echo the raw git diff
      - name: echo raw diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.raw-diff }}
        run: echo $DIFF

      # Upload the json diff as an artifact
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v3
        with:
          name: json-diff
          path: ~/diff.json
          retention-days: 1
